In [1]:
library('SelectSim')
library('tidyverse')
library('tictoc')

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
sessionInfo()

R version 4.4.2 (2024-10-31)
Platform: x86_64-conda-linux-gnu
Running under: AlmaLinux 9.3 (Shamrock Pampas Cat)

Matrix products: default
BLAS/LAPACK: /mnt/ndata/arvind/envs/selectsim_R/lib/libopenblasp-r0.3.29.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] tictoc_1.2.1      lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1
 [5] dplyr_1.1.4       purrr_1.0.4       readr_2.1.5       tidyr_1.3.1
 [9] tibble_3.2.1      ggplot2_3.5.1     tidyverse_2.0.0   SelectSim_0.0.1.5

loaded via a namespace (and not attached):
 [1] gtable_0.3.6       rstatix_0.7.2      lattice_0.22-6     tzdb_0.5.0
 [5] vctrs_0.6.5        tools_4.4.2        generics_0.1.3     parallel_4.4.2
 [9] pkgconfig_2.0.3    Matrix_1.7-3       ggridges_0.5.6     rngtools_1.5.2
[13] RcppParallel_5.1.9 uuid_1.2-1         lifecycle_1.0.4    compiler_4.4.2
[17] munsell_0.5.1      repr_1.1.7         codetools_0.2-20   carData_3.0-5
[21] htmltools_0.5.8.1  Formula_1.2-5      pillar_1.10.1      car_3.1-3
[25] ggpubr_0.6.0       crayon_1.5.3       doRNG_1.8.6.2      iterators_1.0.14
[29] abind_1.4-5        foreach_1.5.2      tidyselect_1.2.1   digest_0.6.37
[33] stringi_1.8.7      reshape2_1.4.4     fastmap_1.2.0      grid_4.4.2
[37] colorspace_2.1-1   cli_3.6.4          magrittr_2.0.3     base64enc_0.1-3
[41] Rfast_2.1.0        IRdisplay_1.1      broom_1.0.8        withr_3.0.2
[45] scales_1.3.0       backports_1.5.0    IRkernel_1.3.2     RcppZiggurat_0.1.8
[49] timechange_0.3.0   pbdZMQ_0.3-13      ggsignif_0.6.4     hms_1.1.3
[53] evaluate_1.0.3     doParallel_1.0.17  rlang_1.1.5        Rcpp_1.0.14
[57] glue_1.8.0         jsonlite_2.0.0     R6_2.6.1           plyr_1.8.9

# Metadata

In [3]:
all_merged_metdata <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/all_merged_data_genie_v15.rds')
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples<-readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/genie/msk_one_patient_one_sample_final.rds')

In [4]:
msk_run_gene_list <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/analysis/catalogue/data/msk_oncokb_gene_run_list.rds')

In [5]:
head(all_merged_metdata,1)

  sample          class tumor_run oncotree cancer_type              race
1 TCGA-OR-A5J5-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
  cohort tumor_run_mapped Tissue        final_tumor_run_mapped
1 TCGA   No mapping       Adrenal Gland ACC

In [6]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

## All panel gams runs

In [7]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(1)

  PATIENT_ID          SEX    PRIMARY_RACE ETHNICITY                CENTER
1 GENIE-MSK-P-0000223 Female White        Non-Spanish/non-Hispanic MSK
  INT_CONTACT INT_DOD YEAR_CONTACT DEAD YEAR_DEATH ⋯ ONCOTREE_CODE SAMPLE_TYPE
1 11142       11142   2016         TRUE 2016       ⋯ AASTR         Primary
  SEQ_ASSAY_ID  CANCER_TYPE CANCER_TYPE_DETAILED   SAMPLE_TYPE_DETAILED class
1 MSK-IMPACT341 Glioma      Anaplastic Astrocytoma Primary tumor        AASTR
  Tumor_run_group final_class      final_run_group
1 AASTR           Glioma_low_grade Glioma

In [8]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

In [9]:
assay_id<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$SEQ_ASSAY_ID)

In [10]:
tumor_groups<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$final_run_group)

In [11]:
cleaned_tumor_groups <- tolower(gsub("[[:space:]/-]", "_", tumor_groups))

In [12]:
mapped_tumor_groups <- cleaned_tumor_groups
names(mapped_tumor_groups)<-tumor_groups

In [13]:
str(mapped_tumor_groups)

 Named chr [1:33] "glioma" "melanoma" "salivary_gland_cancer" "leukemia" ...
 - attr(*, "names")= chr [1:33] "Glioma" "Melanoma" "Salivary Gland Cancer" "Leukemia" ...

In [14]:
pan_can_result <- list()

In [15]:
k=1
dir='/mnt/ndata/arvind/co_mutation_project_revision/catalogue/'
tic('Total Time')
for(name in names(msk_run_gene_list)){
    cat('--Running:',name,"--\n")
    if(name=='all'){
        label<-paste(dir,'/results/','msk_panel_',name,'_primary_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='all') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
        label<-paste(dir,'/results/','msk_panel_',name,'_meta_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='all') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
    }
    else if(name=='p_505'){
        label<-paste(dir,'/results/','msk_panel_',name,'_primary_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_505') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
        label<-paste(dir,'/results/','msk_panel_',name,'_meta_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_505') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
    }
    else if(name=='p_468'){
        label<-paste(dir,'/results/','msk_panel_',name,'_primary_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_468') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
        label<-paste(dir,'/results/','msk_panel_',name,'_meta_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_468') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
    }
    else if(name=='p_410'){
        label<-paste(dir,'/results/','msk_panel_',name,'_primary_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_410') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
        label<-paste(dir,'/results/','msk_panel_',name,'_meta_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_410') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
    }
    else if(name=='p_341'){
        label<-paste(dir,'/results/','msk_panel_',name,'_primary_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_341') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
        label<-paste(dir,'/results/','msk_panel_',name,'_meta_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_341') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
    }
    else{
        name<-'heme'
        label<-paste(dir,'/results/','msk_panel_',name,'_primary_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='heme') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
        label<-paste(dir,'/results/','msk_panel_',name,'_meta_result.rds',sep="")
        msk_result<-readRDS(file = label)
        result_df <- msk_result$result
        result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='heme') %>% mutate('Tumor_run'='Pan-can')
        pan_can_result[[k]]<-result_df
        rm(msk_result)
        k=k+1
    }
 cat('\n---Done---\n')
}
toc()

--Running: all --

---Done---
--Running: p_505 --

---Done---
--Running: p_468 --

---Done---
--Running: p_410 --

---Done---
--Running: p_341 --

---Done---
--Running: p_heme --

---Done---
Total Time: 446.794 sec elapsed

In [19]:
length(pan_can_result)

[1] 12

In [17]:
pan_can_result_msk <- bind_rows(pan_can_result)
rownames(pan_can_result_msk) <- c(1:nrow(pan_can_result_msk))

In [22]:
head(pan_can_result_msk,2)

  SFE_1  SFE_2 name          support_1 support_2 freq_1     freq_2    overlap
1 PIK3CA TP53  PIK3CA - TP53 3970      12075     0.14267745 0.4339623 1429
2 EGFR   KRAS  EGFR - KRAS   1259       5622     0.04524708 0.2020485   36
  w_overlap  max_overlap ⋯ nES       mean_r_nES nFDR cum_freq nFDR2 type FDR
1 1055.34778 3243        ⋯ -295.4658 -13.202552 0    16045    0     ME   TRUE
2   15.12377 1032        ⋯ -192.5590  -6.224075 0     6881    0     ME   TRUE
  Cohort      Panel Tumor_run
1 MSK Primary all   Pan-can
2 MSK Primary all   Pan-can

# Tumor Group Runs

## Primary

In [23]:
tumor_can_result_primary <- list()

In [24]:
k=1
dir='/mnt/ndata/arvind/co_mutation_project_revision/catalogue/'
for(name in names(msk_run_gene_list)){
    cat('--Running:',name,"--\n")
    if(name=='all'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='all') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_primary[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_505'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT505'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_505') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_primary[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_468'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT468'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_468') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_primary[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        } 
    }
    else if(name=='p_410'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT410'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_410') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_primary[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   

    }
    else if(name=='p_341'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT341'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='p_341') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_primary[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
    else{
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID %in% c('MSK-IMPACT-HEME-400','MSK-IMPACT-HEME-468') & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],'heme',sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Primary') %>% mutate('Panel'='heme') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_primary[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
 cat('\n---Done---\n')
}

--Running: all --
---Tumor Group--- Glioma --
---Tumor Group--- Glioma --Done--
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Salivary Gland Cancer --
---Tumor Group--- Salivary Gland Cancer --Done--
---Tumor Group--- Leukemia --
---Tumor Group--- Leukemia --Done--
---Tumor Group--- Anal Cancer --
---Tumor Group--- Anal Cancer --Done--
---Tumor Group--- Appendiceal Cancer --
---Tumor Group--- Appendiceal Cancer --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- B-Lymphoblastic Leukemia/Lymphoma --
---Tumor Group--- B-Lymphoblastic Leukemia/Lymphoma --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Cervical Cancer --
---Tumor Group--- Cervical Cancer --Done--
---Tumor Group--- Billary Tract Cancer --
---Tumor Group--- Billary Tract Cancer --Done--
---Tumor Group--- Mature B-Cell Neoplasms --
---Tumor Group--- Mature B-Cell Neoplasms --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Skin Cancer, Non-Melanoma --
---Tumor Group--- Skin Cancer, Non-Melanoma --Done--
---Tumor Group--- Soft Tissue Sarcoma --
---Tumor Group--- Soft Tissue Sarcoma --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Gastrointestinal Stromal Tumor --
---Tumor Group--- Gastrointestinal Stromal Tumor --Done--
---Tumor Group--- Liver Cancer --
---Tumor Group--- Liver Cancer --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Germ Cell Tumor --
---Tumor Group--- Germ Cell Tumor --Done--
---Tumor Group--- Myeloproliferative Neoplasms --
---Tumor Group--- Myeloproliferative Neoplasms --Done--
---Tumor Group--- Peripheral Nervous System --
---Tumor Group--- Peripheral Nervous System --Done--
---Tumor Group--- Bone Cancer --
---Tumor Group--- Bone Cancer --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Mesothelioma --
---Tumor Group--- Mesothelioma --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Small Cell Lung Cancer --
---Tumor Group--- Small Cell Lung Cancer --Done--
---Tumor Group--- Thyroid Cancer --
---Tumor Group--- Thyroid Cancer --Done--
---Tumor Group--- Endometrial Cancer --
---Tumor Group--- Endometrial Cancer --Done--
---Tumor Group--- Uterine Sarcoma --
---Tumor Group--- Uterine Sarcoma --Done--

---Done---
--Running: p_505 --
---Tumor Group--- Glioma --
---Tumor Group--- Glioma --Done--
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Anal Cancer --
---Tumor Group--- Anal Cancer --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Cervical Cancer --
---Tumor Group--- Cervical Cancer --Done--
---Tumor Group--- Billary Tract Cancer --
---Tumor Group--- Billary Tract Cancer --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Soft Tissue Sarcoma --
---Tumor Group--- Soft Tissue Sarcoma --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Gastrointestinal Stromal Tumor --
---Tumor Group--- Gastrointestinal Stromal Tumor --Done--
---Tumor Group--- Liver Cancer --
---Tumor Group--- Liver Cancer --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Peripheral Nervous System --
---Tumor Group--- Peripheral Nervous System --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Small Cell Lung Cancer --
---Tumor Group--- Small Cell Lung Cancer --Done--
---Tumor Group--- Thyroid Cancer --
---Tumor Group--- Thyroid Cancer --Done--
---Tumor Group--- Endometrial Cancer --
---Tumor Group--- Endometrial Cancer --Done--

---Done---
--Running: p_468 --
---Tumor Group--- Glioma --
---Tumor Group--- Glioma --Done--
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Salivary Gland Cancer --
---Tumor Group--- Salivary Gland Cancer --Done--
---Tumor Group--- Anal Cancer --
---Tumor Group--- Anal Cancer --Done--
---Tumor Group--- Appendiceal Cancer --
---Tumor Group--- Appendiceal Cancer --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Cervical Cancer --
---Tumor Group--- Cervical Cancer --Done--
---Tumor Group--- Billary Tract Cancer --
---Tumor Group--- Billary Tract Cancer --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Soft Tissue Sarcoma --
---Tumor Group--- Soft Tissue Sarcoma --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Gastrointestinal Stromal Tumor --
---Tumor Group--- Gastrointestinal Stromal Tumor --Done--
---Tumor Group--- Liver Cancer --
---Tumor Group--- Liver Cancer --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Germ Cell Tumor --
---Tumor Group--- Germ Cell Tumor --Done--
---Tumor Group--- Peripheral Nervous System --
---Tumor Group--- Peripheral Nervous System --Done--
---Tumor Group--- Bone Cancer --
---Tumor Group--- Bone Cancer --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Mesothelioma --
---Tumor Group--- Mesothelioma --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Small Cell Lung Cancer --
---Tumor Group--- Small Cell Lung Cancer --Done--
---Tumor Group--- Thyroid Cancer --
---Tumor Group--- Thyroid Cancer --Done--
---Tumor Group--- Endometrial Cancer --
---Tumor Group--- Endometrial Cancer --Done--
---Tumor Group--- Uterine Sarcoma --
---Tumor Group--- Uterine Sarcoma --Done--

---Done---
--Running: p_410 --
---Tumor Group--- Glioma --
---Tumor Group--- Glioma --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Billary Tract Cancer --
---Tumor Group--- Billary Tract Cancer --Done--
---Tumor Group--- Mature B-Cell Neoplasms --
---Tumor Group--- Mature B-Cell Neoplasms --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Gastrointestinal Stromal Tumor --
---Tumor Group--- Gastrointestinal Stromal Tumor --Done--
---Tumor Group--- Liver Cancer --
---Tumor Group--- Liver Cancer --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Endometrial Cancer --
---Tumor Group--- Endometrial Cancer --Done--

---Done---
--Running: p_341 --
---Tumor Group--- Glioma --
---Tumor Group--- Glioma --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--

---Done---
--Running: p_heme --
---Tumor Group--- Leukemia --
---Tumor Group--- Leukemia --Done--
---Tumor Group--- B-Lymphoblastic Leukemia/Lymphoma --
---Tumor Group--- B-Lymphoblastic Leukemia/Lymphoma --Done--
---Tumor Group--- Mature B-Cell Neoplasms --
---Tumor Group--- Mature B-Cell Neoplasms --Done--
---Tumor Group--- Myeloproliferative Neoplasms --
---Tumor Group--- Myeloproliferative Neoplasms --Done--

---Done---

In [25]:
length(tumor_can_result_primary)

[1] 109

In [26]:
tumor_can_result_msk_primary <- bind_rows(tumor_can_result_primary)
rownames(tumor_can_result_msk_primary) <- c(1:nrow(tumor_can_result_msk_primary))

In [27]:
head(tumor_can_result_msk_primary,2)

  SFE_1 SFE_2 name        support_1 support_2 freq_1    freq_2    overlap
1 ATRX  IDH1  ATRX - IDH1 222       338       0.1498987 0.2282242 178
2 ATRX  TP53  ATRX - TP53 222       517       0.1498987 0.3490885 186
  w_overlap max_overlap ⋯ nES      mean_r_nES nFDR cum_freq nFDR2 type FDR
1 138.0818  215         ⋯ 47.36808 2.778068   0    560      0     CO   TRUE
2 140.9091  222         ⋯ 42.86324 2.960184   0    739      0     CO   TRUE
  Cohort      Panel Tumor_run
1 MSK Primary all   glioma
2 MSK Primary all   glioma

## Metastasis

In [28]:
tumor_can_result_met <- list()

In [29]:
k=1
dir='/mnt/ndata/arvind/co_mutation_project_revision/catalogue/'
for(name in names(msk_run_gene_list)){
    cat('--Running:',name,"--\n")
    if(name=='all'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='all') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_met[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_505'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT505'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_505') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_met[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_468'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT468'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_468') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_met[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        } 
    }
    else if(name=='p_410'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT410'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_410') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_met[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   

    }
    else if(name=='p_341'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT341'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='p_341') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_met[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
    else{
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID %in% c('MSK-IMPACT-HEME-400','MSK-IMPACT-HEME-468') & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    finalname<-paste(mapped_tumor_groups[tumor_group],'heme',sep="_")
                    label<-paste(dir,'/results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    msk_result<-readRDS(file = label)
                    result_df <- msk_result$result
                    result_df <- result_df %>% mutate('Cohort'='MSK Metastasis') %>% mutate('Panel'='heme') %>% mutate('Tumor_run'=mapped_tumor_groups[tumor_group])
                    tumor_can_result_met[[k]]<-result_df
                    rm(msk_result)
                    k=k+1
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
 cat('\n---Done---\n')
}

--Running: all --
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Salivary Gland Cancer --
---Tumor Group--- Salivary Gland Cancer --Done--
---Tumor Group--- Anal Cancer --
---Tumor Group--- Anal Cancer --Done--
---Tumor Group--- Appendiceal Cancer --
---Tumor Group--- Appendiceal Cancer --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- B-Lymphoblastic Leukemia/Lymphoma --
---Tumor Group--- B-Lymphoblastic Leukemia/Lymphoma --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Cervical Cancer --
---Tumor Group--- Cervical Cancer --Done--
---Tumor Group--- Billary Tract Cancer --
---Tumor Group--- Billary Tract Cancer --Done--
---Tumor Group--- Mature B-Cell Neoplasms --
---Tumor Group--- Mature B-Cell Neoplasms --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Skin Cancer, Non-Melanoma --
---Tumor Group--- Skin Cancer, Non-Melanoma --Done--
---Tumor Group--- Soft Tissue Sarcoma --
---Tumor Group--- Soft Tissue Sarcoma --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Gastrointestinal Stromal Tumor --
---Tumor Group--- Gastrointestinal Stromal Tumor --Done--
---Tumor Group--- Liver Cancer --
---Tumor Group--- Liver Cancer --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Germ Cell Tumor --
---Tumor Group--- Germ Cell Tumor --Done--
---Tumor Group--- Peripheral Nervous System --
---Tumor Group--- Peripheral Nervous System --Done--
---Tumor Group--- Bone Cancer --
---Tumor Group--- Bone Cancer --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Small Cell Lung Cancer --
---Tumor Group--- Small Cell Lung Cancer --Done--
---Tumor Group--- Thyroid Cancer --
---Tumor Group--- Thyroid Cancer --Done--
---Tumor Group--- Endometrial Cancer --
---Tumor Group--- Endometrial Cancer --Done--
---Tumor Group--- Uterine Sarcoma --
---Tumor Group--- Uterine Sarcoma --Done--

---Done---
--Running: p_505 --
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Billary Tract Cancer --
---Tumor Group--- Billary Tract Cancer --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Soft Tissue Sarcoma --
---Tumor Group--- Soft Tissue Sarcoma --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Small Cell Lung Cancer --
---Tumor Group--- Small Cell Lung Cancer --Done--
---Tumor Group--- Thyroid Cancer --
---Tumor Group--- Thyroid Cancer --Done--
---Tumor Group--- Endometrial Cancer --
---Tumor Group--- Endometrial Cancer --Done--

---Done---
--Running: p_468 --
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Salivary Gland Cancer --
---Tumor Group--- Salivary Gland Cancer --Done--
---Tumor Group--- Appendiceal Cancer --
---Tumor Group--- Appendiceal Cancer --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Cervical Cancer --
---Tumor Group--- Cervical Cancer --Done--
---Tumor Group--- Billary Tract Cancer --
---Tumor Group--- Billary Tract Cancer --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Soft Tissue Sarcoma --
---Tumor Group--- Soft Tissue Sarcoma --Done--
---Tumor Group--- Esophagogastric Cancer --
---Tumor Group--- Esophagogastric Cancer --Done--
---Tumor Group--- Gastrointestinal Stromal Tumor --
---Tumor Group--- Gastrointestinal Stromal Tumor --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Peripheral Nervous System --
---Tumor Group--- Peripheral Nervous System --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Small Cell Lung Cancer --
---Tumor Group--- Small Cell Lung Cancer --Done--
---Tumor Group--- Thyroid Cancer --
---Tumor Group--- Thyroid Cancer --Done--
---Tumor Group--- Endometrial Cancer --
---Tumor Group--- Endometrial Cancer --Done--
---Tumor Group--- Uterine Sarcoma --
---Tumor Group--- Uterine Sarcoma --Done--

---Done---
--Running: p_410 --
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Bladder Cancer --
---Tumor Group--- Bladder Cancer --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Renal Cell Carcinoma --
---Tumor Group--- Renal Cell Carcinoma --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Gastrointestinal Stromal Tumor --
---Tumor Group--- Gastrointestinal Stromal Tumor --Done--
---Tumor Group--- Head and Neck Cancer --
---Tumor Group--- Head and Neck Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Pancreatic Cancer --
---Tumor Group--- Pancreatic Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--
---Tumor Group--- Small Cell Lung Cancer --
---Tumor Group--- Small Cell Lung Cancer --Done--
---Tumor Group--- Thyroid Cancer --
---Tumor Group--- Thyroid Cancer --Done--

---Done---
--Running: p_341 --
---Tumor Group--- Melanoma --
---Tumor Group--- Melanoma --Done--
---Tumor Group--- Breast Cancer --
---Tumor Group--- Breast Cancer --Done--
---Tumor Group--- Ovarian Cancer --
---Tumor Group--- Ovarian Cancer --Done--
---Tumor Group--- Colorectal Cancer --
---Tumor Group--- Colorectal Cancer --Done--
---Tumor Group--- Non-Small Cell Lung Cancer --
---Tumor Group--- Non-Small Cell Lung Cancer --Done--
---Tumor Group--- Prostate Cancer --
---Tumor Group--- Prostate Cancer --Done--

---Done---
--Running: p_heme --
---Tumor Group--- Mature B-Cell Neoplasms --
---Tumor Group--- Mature B-Cell Neoplasms --Done--

---Done---

In [30]:
length(tumor_can_result_met)

[1] 87

In [31]:
tumor_can_result_msk_met <- bind_rows(tumor_can_result_met)
rownames(tumor_can_result_msk_met) <- c(1:nrow(tumor_can_result_msk_met))

In [32]:
head(tumor_can_result_msk_met,2)

  SFE_1 SFE_2 name        support_1 support_2 freq_1    freq_2    overlap
1 BRAF  NRAS  BRAF - NRAS 404       323       0.3587922 0.2868561 17
2 BRAF  NF1   BRAF - NF1  404       222       0.3587922 0.1971581 31
  w_overlap max_overlap ⋯ nES       mean_r_nES nFDR cum_freq nFDR2 type FDR
1  9.913468 322         ⋯ -39.29476 -2.014066  0    727      0     ME   TRUE
2 11.569570 222         ⋯ -22.11924 -1.581512  0    626      0     ME   TRUE
  Cohort         Panel Tumor_run
1 MSK Metastasis all   melanoma
2 MSK Metastasis all   melanoma

# Merge all result into one dataframe

In [33]:
dim(pan_can_result_msk)

[1] 267963     25

In [34]:
dim(tumor_can_result_msk_primary)

[1] 767015     25

In [35]:
dim(tumor_can_result_msk_met)

[1] 457018     25

In [36]:
all_result_merged_msk <- rbind(pan_can_result_msk,tumor_can_result_msk_primary,tumor_can_result_msk_met)

In [37]:
head(all_result_merged_msk)

  SFE_1  SFE_2 name          support_1 support_2 freq_1     freq_2    overlap
1 PIK3CA TP53  PIK3CA - TP53 3970      12075     0.14267745 0.4339623 1429
2 EGFR   KRAS  EGFR - KRAS   1259       5622     0.04524708 0.2020485   36
3 PTEN   TP53  PTEN - TP53   2469      12075     0.08873315 0.4339623  695
4 ARID1A TP53  ARID1A - TP53 2866      12075     0.10300090 0.4339623  988
5 KRAS   TP53  KRAS - TP53   5622      12075     0.20204852 0.4339623 2773
6 APC    TP53  APC - TP53    3486      12075     0.12528302 0.4339623 2302
  w_overlap  max_overlap ⋯ nES       mean_r_nES nFDR cum_freq nFDR2 type FDR
1 1055.34778 3243        ⋯ -295.4658 -13.202552 0    16045    0     ME   TRUE
2   15.12377 1032        ⋯ -192.5590  -6.224075 0     6881    0     ME   TRUE
3  468.87573 1655        ⋯ -171.9698 -10.024308 0    14544    0     ME   TRUE
4  630.94088 2150        ⋯ -167.5421 -10.254287 0    14941    0     ME   TRUE
5 2418.48500 5013        ⋯ -133.4159 -15.172525 0    17697    0     ME   TRUE
6 1905.36483 3239        ⋯  130.5036  11.979271 0    15561    0     CO   TRUE
  Cohort      Panel Tumor_run
1 MSK Primary all   Pan-can
2 MSK Primary all   Pan-can
3 MSK Primary all   Pan-can
4 MSK Primary all   Pan-can
5 MSK Primary all   Pan-can
6 MSK Primary all   Pan-can

In [38]:
saveRDS(all_result_merged_msk,file='/mnt/ndata/arvind/co_mutation_project_revision/catalogue/results/all_merged_result_msk_v15.rds')