In [1]:
library('SelectSim')
library('tidyverse')

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
sessionInfo()

R version 4.4.2 (2024-10-31)
Platform: x86_64-conda-linux-gnu
Running under: AlmaLinux 9.3 (Shamrock Pampas Cat)

Matrix products: default
BLAS/LAPACK: /mnt/ndata/arvind/envs/selectsim_R/lib/libopenblasp-r0.3.29.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4
 [5] purrr_1.0.4       readr_2.1.5       tidyr_1.3.1       tibble_3.2.1
 [9] ggplot2_3.5.1     tidyverse_2.0.0   SelectSim_0.0.1.5

loaded via a namespace (and not attached):
 [1] gtable_0.3.6       rstatix_0.7.2      lattice_0.22-6     tzdb_0.5.0
 [5] vctrs_0.6.5        tools_4.4.2        generics_0.1.3     parallel_4.4.2
 [9] pkgconfig_2.0.3    Matrix_1.7-3       ggridges_0.5.6     rngtools_1.5.2
[13] RcppParallel_5.1.9 uuid_1.2-1         lifecycle_1.0.4    compiler_4.4.2
[17] tictoc_1.2.1       munsell_0.5.1      repr_1.1.7         codetools_0.2-20
[21] carData_3.0-5      htmltools_0.5.8.1  Formula_1.2-5      pillar_1.10.1
[25] car_3.1-3          ggpubr_0.6.0       crayon_1.5.3       doRNG_1.8.6.2
[29] iterators_1.0.14   abind_1.4-5        foreach_1.5.2      tidyselect_1.2.1
[33] digest_0.6.37      stringi_1.8.7      reshape2_1.4.4     fastmap_1.2.0
[37] grid_4.4.2         colorspace_2.1-1   cli_3.6.4          magrittr_2.0.3
[41] base64enc_0.1-3    Rfast_2.1.0        IRdisplay_1.1      broom_1.0.8
[45] withr_3.0.2        scales_1.3.0       backports_1.5.0    IRkernel_1.3.2
[49] RcppZiggurat_0.1.8 timechange_0.3.0   pbdZMQ_0.3-13      ggsignif_0.6.4
[53] hms_1.1.3          evaluate_1.0.3     doParallel_1.0.17  rlang_1.1.5
[57] Rcpp_1.0.14        glue_1.8.0         jsonlite_2.0.0     R6_2.6.1
[61] plyr_1.8.9

#  Functions

In [3]:
# Filter the pan_can_run data object to required needs.
filter_run_data <- function(run_data,gene_order,sample_order){
    final_run_data<-run_data
    final_run_data$M$M$missense<-run_data$M$M$missense[gene_order,sample_order]
    final_run_data$M$M$truncating<-run_data$M$M$truncating[gene_order,sample_order]
    final_run_data$alteration.class<- run_data$alteration.class[gene_order]
    final_run_data$sample.class<-run_data$sample.class[sample_order]
    final_run_data$M$tmb$missense<-run_data$M$tmb$missense[sample_order,]
    final_run_data$M$tmb$truncating<-run_data$M$tmb$truncating[sample_order,]
    return(final_run_data)
}

# Metadata

In [4]:
all_merged_metdata <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/all_merged_data_genie_v15.rds')
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples<-readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/genie/msk_one_patient_one_sample_final.rds')
genie_metadata_15_dfci_with_mutation_selected_final_atleast_100_samples<-readRDS(file='/mnt/ndata/arvind/co_mutation_project/data/processed/genie/dfci_one_patient_one_sample_final.rds')

In [5]:
msk_run_gene_list <- readRDS(file='/mnt/ndata/arvind/co_mutation_project/analysis/catalogue/data/msk_oncokb_gene_run_list.rds')

In [6]:
head(all_merged_metdata,1)

  sample          class tumor_run oncotree cancer_type              race
1 TCGA-OR-A5J5-01 ACC   ACC       ACC      Adrenocortical Carcinoma White
  cohort tumor_run_mapped Tissue        final_tumor_run_mapped
1 TCGA   No mapping       Adrenal Gland ACC

In [7]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

# Pan-Cancer Runs

## MSK Primary run

In [8]:
msk_run_p_data <- readRDS('/mnt/ndata/arvind/co_mutation_project/data/processed/gams/pan_can_msk_primary_run_data_v15.rds')

In [9]:
str(msk_run_p_data)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:396, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. ..$ truncating: num [1:396, 1:27825] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 4 4 1 0 4 2 3 3 2 3 ...
  .. ..$ truncating:'data.frame':	27825 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
  .. .. ..$ mutation: num [1:27825] 1 3 0 3 1 0 0 0 0 2 ...
 $ sample.class    : Named chr [1:27825] "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" ...
  ..- attr(*, "names")= chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...
 $ alteration.class: Named chr [1:396] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:396] "AKT1" "ALK" "APC" "AR" ...

In [10]:
table(msk_run_p_data$sample.class)
length(table(msk_run_p_data$sample.class))

            ACRM             ACYC              AML             ANSC
              39               67              118               96
            APAD             BLCA              BLL             CCOV
              60             1273              117              105
            CESC             CHOL           CLLSLL           CRC_HM
             108              107              265              610
          CRC_LM             CSCC             DDLS         DLBCLNOS
            3530               67              117              357
            EHCH             ESCA             ESCC               FL
              81              740               83              321
            GBAD              GBC              GBM             GIST
              60               62             1045              354
Glioma_low_grade              HCC            HGSFT            HGSOC
             436              264               88              610
            HNSC              IDC             IHCH              ILC
             236             2339              417              288
           LGSOC              LMS             LUAD             LUNE
              46              115             3049               51
            LUSC             MAAP              MBN              MCC
             543               61               99               55
             MCL              MEL              MFH             MGCT
             167              389              148               66
             MPN              NBL            NSCLC               OS
              85              131              207               64
            PAAD            PANET          PLEMESO             PRAD
            1834              118              126             1805
             RCC          SARCNOS             SCLC              SEM
             520              191              195               71
            STAD             THAP             THPA             THPD
             411               81              154               98
         UCEC_HM          UCEC_LM              UCS             ULMS
             510             1055              226               96
              UM              USC             UTUC
              47              336              215

[1] 67

In [11]:
str(msk_run_p_data$sample.class)

 Named chr [1:27825] "Glioma_low_grade" "Glioma_low_grade" ...
 - attr(*, "names")= chr [1:27825] "GENIE-MSK-P-0000223-T01-IM3" "GENIE-MSK-P-0000679-T01-IM3" "GENIE-MSK-P-0000748-T01-IM3" "GENIE-MSK-P-0001408-T01-IM3" ...

In [12]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(1)

  PATIENT_ID          SEX    PRIMARY_RACE ETHNICITY                CENTER
1 GENIE-MSK-P-0000223 Female White        Non-Spanish/non-Hispanic MSK
  INT_CONTACT INT_DOD YEAR_CONTACT DEAD YEAR_DEATH ⋯ ONCOTREE_CODE SAMPLE_TYPE
1 11142       11142   2016         TRUE 2016       ⋯ AASTR         Primary
  SEQ_ASSAY_ID  CANCER_TYPE CANCER_TYPE_DETAILED   SAMPLE_TYPE_DETAILED class
1 MSK-IMPACT341 Glioma      Anaplastic Astrocytoma Primary tumor        AASTR
  Tumor_run_group final_class      final_run_group
1 AASTR           Glioma_low_grade Glioma

In [13]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

In [14]:
assay_id<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$SEQ_ASSAY_ID)

In [15]:
assay_id

[1] "MSK-IMPACT341"       "MSK-IMPACT410"       "MSK-IMPACT468"
[4] "MSK-IMPACT505"       "MSK-IMPACT-HEME-400" "MSK-IMPACT-HEME-468"

In [ ]:
# This cell will generate the results for each panel SelectSim Results
for(name in names(msk_run_gene_list)){
    cat('--Running:',name,"--\n")
    if(name=='all'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% filter(SAMPLE_TYPE=='Primary'))$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_p_data,
                               gene_order = msk_run_gene_list$all,
                               sample_order =samples ) 
        #label<-paste('../data/','msk_panel_',name,'_primary_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)
        label<-paste('../results/','msk_panel_',name,'_primary_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else if(name=='p_505'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE=='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT505') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_p_data,
                               gene_order = msk_run_gene_list$p_505,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_primary_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_primary_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else 
    if(name=='p_468'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE=='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT468') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_p_data,
                               gene_order = msk_run_gene_list$p_468,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_primary_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_primary_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else if(name=='p_410'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE=='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT410') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_p_data,
                               gene_order = msk_run_gene_list$p_410,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_primary_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_primary_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else if(name=='p_341'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE=='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT341') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_p_data,
                               gene_order = msk_run_gene_list$p_341,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_primary_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_primary_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else{
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
        filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID %in% c('MSK-IMPACT-HEME-400','MSK-IMPACT-HEME-468')) %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_p_data,
                               gene_order = msk_run_gene_list$p_heme,
                               sample_order =samples) 
        name<-'heme'
        #label<-paste('../data/','msk_panel_',name,'_primary_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_primary_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
 cat('\n---Done---\n')
}

## MSK Metastatsis

In [17]:
msk_run_m_data <- readRDS('/mnt/ndata/arvind/co_mutation_project/data/processed/gams/pan_can_msk_meta_run_data_v15.rds')

In [18]:
str(msk_run_m_data)

List of 3
 $ M               :List of 2
  ..$ M  :List of 2
  .. ..$ missense  : num [1:396, 1:14965] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:14965] "GENIE-MSK-P-0020921-T01-IM6" "GENIE-MSK-P-0027135-T01-IM6" "GENIE-MSK-P-0045988-T02-IM6" "GENIE-MSK-P-0001029-T01-IM3" ...
  .. ..$ truncating: num [1:396, 1:14965] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:396] "AKT1" "ALK" "APC" "AR" ...
  .. .. .. ..$ : chr [1:14965] "GENIE-MSK-P-0020921-T01-IM6" "GENIE-MSK-P-0027135-T01-IM6" "GENIE-MSK-P-0045988-T02-IM6" "GENIE-MSK-P-0001029-T01-IM3" ...
  ..$ tmb:List of 2
  .. ..$ missense  :'data.frame':	14965 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:14965] "GENIE-MSK-P-0020921-T01-IM6" "GENIE-MSK-P-0027135-T01-IM6" "GENIE-MSK-P-0045988-T02-IM6" "GENIE-MSK-P-0001029-T01-IM3" ...
  .. .. ..$ mutation: num [1:14965] 7 3 1 1 1 3 2 6 1 1 ...
  .. ..$ truncating:'data.frame':	14965 obs. of  2 variables:
  .. .. ..$ sample  : chr [1:14965] "GENIE-MSK-P-0020921-T01-IM6" "GENIE-MSK-P-0027135-T01-IM6" "GENIE-MSK-P-0045988-T02-IM6" "GENIE-MSK-P-0001029-T01-IM3" ...
  .. .. ..$ mutation: num [1:14965] 2 3 1 1 0 0 0 1 3 1 ...
 $ sample.class    : Named chr [1:14965] "Glioma_low_grade" "Glioma_low_grade" "Glioma_low_grade" "ACRM" ...
  ..- attr(*, "names")= chr [1:14965] "GENIE-MSK-P-0020921-T01-IM6" "GENIE-MSK-P-0027135-T01-IM6" "GENIE-MSK-P-0045988-T02-IM6" "GENIE-MSK-P-0001029-T01-IM3" ...
 $ alteration.class: Named chr [1:396] "MUT" "MUT" "MUT" "MUT" ...
  ..- attr(*, "names")= chr [1:396] "AKT1" "ALK" "APC" "AR" ...

In [19]:
table(msk_run_m_data$sample.class)
length(table(msk_run_m_data$sample.class))

            ACRM             ACYC              AML             ANSC
              62              112               23               54
            APAD             BLCA              BLL             CCOV
              60              211               30               49
            CESC             CHOL           CLLSLL           CRC_HM
              50               81               70               56
          CRC_LM             CSCC             DDLS         DLBCLNOS
            1495               55               59               72
            EHCH             ESCA             ESCC               FL
              44              176               29               52
            GBAD              GBC              GBM             GIST
              41               68               24              119
Glioma_low_grade              HCC            HGSFT            HGSOC
              17               38               47              988
            HNSC              IDC             IHCH              ILC
             215             2275               98              271
           LGSOC              LMS             LUAD             LUNE
              60              121             1780               67
            LUSC             MAAP              MBN              MCC
             196               85                8               45
             MCL              MEL              MFH             MGCT
              35              989               69               57
             MPN              NBL            NSCLC               OS
              24               76              193               53
            PAAD            PANET          PLEMESO             PRAD
            1093              121               15              979
             RCC          SARCNOS             SCLC              SEM
             290               87              231               36
            STAD             THAP             THPA             THPD
             149               38              199               81
         UCEC_HM          UCEC_LM              UCS             ULMS
             100              229               81              101
              UM              USC             UTUC
              75              114               47

[1] 67

In [20]:
str(msk_run_m_data$sample.class)

 Named chr [1:14965] "Glioma_low_grade" "Glioma_low_grade" ...
 - attr(*, "names")= chr [1:14965] "GENIE-MSK-P-0020921-T01-IM6" "GENIE-MSK-P-0027135-T01-IM6" "GENIE-MSK-P-0045988-T02-IM6" "GENIE-MSK-P-0001029-T01-IM3" ...

In [21]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(1)

  PATIENT_ID          SEX    PRIMARY_RACE ETHNICITY                CENTER
1 GENIE-MSK-P-0000223 Female White        Non-Spanish/non-Hispanic MSK
  INT_CONTACT INT_DOD YEAR_CONTACT DEAD YEAR_DEATH ⋯ ONCOTREE_CODE SAMPLE_TYPE
1 11142       11142   2016         TRUE 2016       ⋯ AASTR         Primary
  SEQ_ASSAY_ID  CANCER_TYPE CANCER_TYPE_DETAILED   SAMPLE_TYPE_DETAILED class
1 MSK-IMPACT341 Glioma      Anaplastic Astrocytoma Primary tumor        AASTR
  Tumor_run_group final_class      final_run_group
1 AASTR           Glioma_low_grade Glioma

In [22]:
str(msk_run_gene_list)

List of 6
 $ all   : chr [1:202] "MTOR" "NRAS" "NTRK1" "SDHC" ...
 $ p_505 : chr [1:327] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_468 : chr [1:306] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_410 : chr [1:282] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_341 : chr [1:249] "MTOR" "NRAS" "RIT1" "NTRK1" ...
 $ p_heme: chr [1:267] "MTOR" "NRAS" "CD58" "NTRK1" ...

In [23]:
assay_id<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$SEQ_ASSAY_ID)

In [24]:
assay_id

[1] "MSK-IMPACT341"       "MSK-IMPACT410"       "MSK-IMPACT468"
[4] "MSK-IMPACT505"       "MSK-IMPACT-HEME-400" "MSK-IMPACT-HEME-468"

In [ ]:
# This cell will generate the results for each panel SelectSim Results
for(name in names(msk_run_gene_list)){
    cat('--Running:',name,"--\n")
    if(name=='all'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% filter(SAMPLE_TYPE!='Primary'))$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_m_data,
                               gene_order = msk_run_gene_list$all,
                               sample_order =samples ) 
        #label<-paste('../data/','msk_panel_',name,'_meta_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)
        label<-paste('../results/','msk_panel_',name,'_meta_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else if(name=='p_505'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE!='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT505') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_m_data,
                               gene_order = msk_run_gene_list$p_505,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_meta_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_meta_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else 
    if(name=='p_468'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE!='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT468') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_m_data,
                               gene_order = msk_run_gene_list$p_468,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_meta_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_meta_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else if(name=='p_410'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE!='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT410') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_m_data,
                               gene_order = msk_run_gene_list$p_410,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_meta_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_meta_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else if(name=='p_341'){
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                  filter(SAMPLE_TYPE!='Primary' &SEQ_ASSAY_ID=='MSK-IMPACT341') %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_m_data,
                               gene_order = msk_run_gene_list$p_341,
                               sample_order =samples) 
        #label<-paste('../data/','msk_panel_',name,'_meta_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_meta_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
    else{
        samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
        filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID %in% c('MSK-IMPACT-HEME-400','MSK-IMPACT-HEME-468')) %>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
        temp<- filter_run_data(run_data = msk_run_m_data,
                               gene_order = msk_run_gene_list$p_heme,
                               sample_order =samples) 
        name<-'heme'
        #label<-paste('../data/','msk_panel_',name,'_meta_run_data.rds',sep="")
        #saveRDS(temp,file = label,compress = TRUE)
        msk_result <- selectX(M = temp$M,
                            sample.class = temp$sample.class,
                            alteration.class = temp$alteration.class,
                            n.cores = 15,
                            min.freq = round(0.001*length(temp$sample.class)),
                            n.permut = 1000,
                            lambda = 0.3,
                            tao = 1,
                            save.object = FALSE,
                            verbose = FALSE,
                            estimate_pairwise = FALSE,
                            maxFDR = 0.25,
                            seed = 42)

        label<-paste('../results/','msk_panel_',name,'_meta_result.rds',sep="")
        saveRDS(msk_result,file = label,compress = TRUE)
        rm(msk_result)
    }
 cat('\n---Done---\n')
}

# Tumor Group Runs

## MSK Primary run

In [ ]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(1)

In [ ]:
str(msk_run_gene_list)

In [ ]:
assay_id<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$SEQ_ASSAY_ID)

In [ ]:
assay_id

In [ ]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(2)

In [ ]:
tumor_groups<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$final_run_group)

In [ ]:
cleaned_tumor_groups <- tolower(gsub("[[:space:]/-]", "_", tumor_groups))

In [ ]:
mapped_tumor_groups <- cleaned_tumor_groups
names(mapped_tumor_groups)<-tumor_groups

In [ ]:
str(mapped_tumor_groups)

In [ ]:
for(name in names(msk_run_gene_list)){
    cat('--Running:',name,"--\n")
    if(name=='all'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_p_data,
                                           gene_order = msk_run_gene_list$all,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_primary_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_505'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT505'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_p_data,
                                           gene_order = msk_run_gene_list$p_505,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_primary_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_468'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT468'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_p_data,
                                           gene_order = msk_run_gene_list$p_468,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_primary_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        } 
    }
    else if(name=='p_410'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT410'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_p_data,
                                           gene_order = msk_run_gene_list$p_410,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_primary_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   

    }
    else if(name=='p_341'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT341'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_p_data,
                                           gene_order = msk_run_gene_list$p_341,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_primary_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
    else{
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE=='Primary' & SEQ_ASSAY_ID %in% c('MSK-IMPACT-HEME-400','MSK-IMPACT-HEME-468') & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_p_data,
                                           gene_order = msk_run_gene_list$p_heme,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],'heme',sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_primary_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_primary_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
 cat('\n---Done---\n')
}

## MSK-Metastasis

In [ ]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(1)

In [ ]:
str(msk_run_gene_list)

In [ ]:
assay_id<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$SEQ_ASSAY_ID)

In [ ]:
assay_id

In [ ]:
genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% head(2)

In [ ]:
tumor_groups<-unique(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples$final_run_group)

In [ ]:
cleaned_tumor_groups <- tolower(gsub("[[:space:]/-]", "_", tumor_groups))

In [ ]:
mapped_tumor_groups <- cleaned_tumor_groups
names(mapped_tumor_groups)<-tumor_groups

In [ ]:
str(mapped_tumor_groups)

In [ ]:
for(name in names(msk_run_gene_list)){
    cat('--Running:',name,"--\n")
    if(name=='all'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_m_data,
                                           gene_order = msk_run_gene_list$all,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_meta_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_505'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT505'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_m_data,
                                           gene_order = msk_run_gene_list$p_505,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_meta_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }    

    }
    else if(name=='p_468'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT468'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_m_data,
                                           gene_order = msk_run_gene_list$p_468,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_meta_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        } 
    }
    else if(name=='p_410'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT410'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_m_data,
                                           gene_order = msk_run_gene_list$p_410,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_meta_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   

    }
    else if(name=='p_341'){
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID=='MSK-IMPACT341'& final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_m_data,
                                           gene_order = msk_run_gene_list$p_341,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],name,sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_meta_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
    else{
        for(tumor_group in names(mapped_tumor_groups)){
            samples<-(genie_metadata_15_msk_with_mutation_selected_final_atleast_100_samples %>% 
                      filter(SAMPLE_TYPE!='Primary' & SEQ_ASSAY_ID %in% c('MSK-IMPACT-HEME-400','MSK-IMPACT-HEME-468') & final_run_group==tumor_group)%>% group_by(final_class) %>% filter(n()>=30) %>% ungroup())$SAMPLE_ID
            if(length(samples)>=30){
                cat('---Tumor Group---',tumor_group,"--\n")
                    temp<- filter_run_data(run_data = msk_run_m_data,
                                           gene_order = msk_run_gene_list$p_heme,
                                           sample_order =samples ) 
                    finalname<-paste(mapped_tumor_groups[tumor_group],'heme',sep="_")
                    #label<-paste('../data/','msk_panel_',finalname,'_meta_run_data.rds',sep="")
                    #saveRDS(temp,file = label,compress = TRUE)
                    msk_result <- selectX(M = temp$M,
                                        sample.class = temp$sample.class,
                                        alteration.class = temp$alteration.class,
                                        n.cores = 15,
                                        min.freq = round(0.001*length(temp$sample.class)),
                                        n.permut = 1000,
                                        lambda = 0.3,
                                        tao = 1,
                                        save.object = FALSE,
                                        verbose = FALSE,
                                        estimate_pairwise = FALSE,
                                        maxFDR = 0.25,
                                        seed = 42)
                    label<-paste('../results/','msk_panel_',finalname,'_meta_result.rds',sep="")
                    saveRDS(msk_result,file = label,compress = TRUE)
                    rm(msk_result)                
                cat('---Tumor Group---',tumor_group,"--Done--\n")        
                
            }
        }   
    }
 cat('\n---Done---\n')
}